# Generated by Django 3.2 on 2025-12-09 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_question_answers_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_answers',
            name='type',
        ),
    ]
