# Generated by Django 3.2 on 2025-12-09 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_question_answers_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='STUDENT',
        ),
    ]
