# Generated by Django 3.2 on 2025-12-09 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_test_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_answers',
            name='score',
            field=models.CharField(max_length=400),
        ),
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=300)),
                ('mark', models.CharField(max_length=300)),
                ('QUESTION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.question_answers')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
    ]
