# Generated by Django 3.2 on 2025-12-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_notes_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='attend',
            name='total_mark',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
